### ISSUE TITLE
Svelte Language Extension Support !! 

### ISSUE THREAD

**Issue by tsrCodes** [thurti/svelte-prism-action#2]
Any Idea for Svelte Language Extension : [Source](https://github.com/pngwn/prism-svelte) Prism Svelte by pngwn

**Comment by thurti** [comment]
Mh, that's right. Custom language definitions are currently not supported because the language file gets loaded from the prismjs components directory. 

I will have a look. Shouldn't be that hard to add.

It's kind of ironic to have a svelte prismjs action which doesn't support highlighting svelte code :D

**Comment by tsrCodes** [comment]
Yeah Kind of !! Take Your Own Time : )

**Comment by kdheepak** [comment]
The ability to add plugins and extensions would be awesome. Is there any status update on this?

**Comment by thurti** [comment]
I have to admit that I had forgotten about that point. Since this is a side project of mine other freelance work have priority for me right now.

I will do it on my todo but I don't know when I will find the time. Maybe by the end of the week. 

Pull Requests are very welcome on this.

**Comment by tsrCodes** [comment]
Finally :) @thurti

**Comment by thurti** [comment]
"end of the week" was a bit optimistic though :D
